# Make sure to check the documentation at https://goreleaser.com
---
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - binary: myks
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
archives:
  - format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - docs/*
checksum:
  name_template: 'checksums.txt'
signs:
  - artifacts: checksum
    cmd: gpg2
    args:
      - '--batch'
      - '-u'
      - '{{ .Env.GPG_FINGERPRINT }}'
      - '--output'
      - '${signature}'
      - '--detach-sign'
      - '${artifact}'
aurs:
  - name: myks-bin
    homepage: https://github.com/mykso/myks
    description: Configuration framework for Kubernetes applications
    maintainers:
      - 'German Lashevich <german.lashevich at gmail dot com>'
    license: 'MIT'
    private_key: '{{ .Env.AUR_SSH_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/myks-bin.git'
    optdepends:
      - 'vendir: for downloading from external sources'
      - 'git: for smart detection of changes'
      - 'helm: for rendering helm charts'
    package: |-
      BIN=myks

      install -Dm755 ./$BIN -t "${pkgdir}/usr/bin"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      ./$BIN completion bash | install -Dm644 /dev/stdin "${pkgdir}/usr/share/bash-completion/completions/$BIN"
      ./$BIN completion fish | install -Dm644 /dev/stdin "${pkgdir}/usr/share/fish/vendor_completions.d/$BIN.fish"
      ./$BIN completion zsh  | install -Dm644 /dev/stdin "${pkgdir}/usr/share/zsh/site-functions/_$BIN"
    commit_author:
      name: Mykso Bot
      email: german.lashevich+mykso-bot@gmail.com
homebrew_casks:
  - name: myks
    description: Configuration framework for Kubernetes applications
    homepage: https://github.com/mykso/myks
    license: MIT
    commit_author:
      name: Mykso Bot
      email: german.lashevich+mykso-bot@gmail.com
    conflicts:
      - formula: myks
    dependencies:
      - formula: git
      - formula: helm
    repository:
      owner: mykso
      name: homebrew-tap
      token: '{{ .Env.HOMEBREW_TAP_REPO_TOKEN }}'
    hooks:
      post:
        # This is a workaround for the quarantine attribute that macOS applies to downloaded files.
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/myks"]
          end
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/mykso/myks:{{ .Tag }}-linux-amd64
      - ghcr.io/mykso/myks:{{ .Major }}-linux-amd64
      - ghcr.io/mykso/myks:{{ .Major }}.{{ .Minor }}-linux-amd64
      - ghcr.io/mykso/myks:latest-linux-amd64
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
  - goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/mykso/myks:{{ .Tag }}-linux-arm64
      - ghcr.io/mykso/myks:{{ .Major }}-linux-arm64
      - ghcr.io/mykso/myks:{{ .Major }}.{{ .Minor }}-linux-arm64
      - ghcr.io/mykso/myks:latest-linux-arm64
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
docker_manifests:
  - name_template: ghcr.io/mykso/myks:{{ .Tag }}
    image_templates:
      - ghcr.io/mykso/myks:{{ .Tag }}-linux-amd64
      - ghcr.io/mykso/myks:{{ .Tag }}-linux-arm64
  - name_template: ghcr.io/mykso/myks:{{ .Major }}
    image_templates:
      - ghcr.io/mykso/myks:{{ .Major }}-linux-amd64
      - ghcr.io/mykso/myks:{{ .Major }}-linux-arm64
  - name_template: ghcr.io/mykso/myks:{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/mykso/myks:{{ .Major }}.{{ .Minor }}-linux-amd64
      - ghcr.io/mykso/myks:{{ .Major }}.{{ .Minor }}-linux-arm64
  - name_template: ghcr.io/mykso/myks:latest
    image_templates:
      - ghcr.io/mykso/myks:latest-linux-amd64
      - ghcr.io/mykso/myks:latest-linux-arm64
nfpms:
  - vendor: Mykso
    homepage: https://github.com/mykso/myks
    maintainer: German Lashevich <german.lashevich@gmail.com>
    description: Configuration framework for Kubernetes applications
    license: MIT
    formats:
      - apk
      - deb
      - rpm
