package myks

import (
	"fmt"
	"maps"
	"math"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
)

// emit writes the seeded KCL tree: kcl.mod, main.k, and one env.k per non-empty level.
func (m *migrator) emit(schemaPackage string) error {
	if err := m.writeKclMod(schemaPackage); err != nil {
		return err
	}
	if err := m.writeMainK(); err != nil {
		return err
	}

	emitted := map[string]bool{}
	for dir, node := range m.nodes {
		emitted[dir] = m.nodeIsEmitted(node)
	}
	for _, dir := range slices.Sorted(maps.Keys(m.nodes)) {
		if !emitted[dir] {
			continue
		}
		node := m.nodes[dir]
		parent := node.parent
		for parent != nil && !emitted[parent.dir] {
			parent = parent.parent
		}
		if err := writeFile(filepath.Join(m.g.RootDir, dir, "env.k"), []byte(m.renderEnvK(node, parent))); err != nil {
			return fmt.Errorf("writing %s/env.k: %w", dir, err)
		}
	}
	return nil
}

// nodeIsEmitted reports whether a level gets its own env.k. The root and the leaves always
// do; an intermediate level only when it carries content (a child package imports its
// nearest emitted ancestor, so empty levels need no file).
func (m *migrator) nodeIsEmitted(node *migNode) bool {
	return node == m.root || node.env != nil ||
		len(node.envValues)+len(node.declared)+len(node.overrides) > 0
}

func (m *migrator) writeKclMod(schemaPackage string) error {
	var dep string
	if strings.HasPrefix(schemaPackage, "oci://") {
		dep = fmt.Sprintf("myks = { oci = %q, tag = %q }", schemaPackage, supportedKclSchemaVersion)
	} else {
		dep = fmt.Sprintf("myks = { path = %q }", filepath.ToSlash(schemaPackage))
	}
	content := fmt.Sprintf(`[package]
name = "config"
version = "0.1.0"

[dependencies]
%s
`, dep)
	return writeFile(filepath.Join(m.g.RootDir, kclModFileName), []byte(content))
}

func (m *migrator) writeMainK() error {
	b := &strings.Builder{}
	b.WriteString("# Generated by `myks migrate`: the root evaluation emitting the frozen resolved tree.\n")
	b.WriteString("# Environments are discovered from this output only — no filesystem walk.\n")
	b.WriteString("import myks\n")

	leafDirs := slices.Sorted(maps.Keys(m.g.environments))
	for i, dir := range leafDirs {
		fmt.Fprintf(b, "import %s as env_%d\n", packagePath(dir), i+1)
	}

	b.WriteString("\nmyksSchemaVersion = myks.SCHEMA_VERSION\n")
	b.WriteString("environments = {\n")
	for i, dir := range leafDirs {
		rel, err := filepath.Rel(m.g.EnvironmentBaseDir, dir)
		if err != nil {
			return fmt.Errorf("resolving environment path %s: %w", dir, err)
		}
		fmt.Fprintf(b, "    %q = env_%d.env\n", filepath.ToSlash(rel), i+1)
	}
	b.WriteString("}\n")

	return writeFile(filepath.Join(m.g.RootDir, "main.k"), []byte(b.String()))
}

func packagePath(dir string) string {
	return strings.ReplaceAll(filepath.ToSlash(dir), "/", ".")
}

// renderEnvK renders one level's env.k. The root instantiates the base schema; every other
// level imports its nearest emitted ancestor and patches it with a dict union.
func (m *migrator) renderEnvK(node, parent *migNode) string {
	b := &strings.Builder{}
	b.WriteString("# Generated by `myks migrate` from the legacy ytt data-values files.\n")
	b.WriteString("# This is a machine seed: see docs/migration.md for the hand-finish steps.\n")

	if node == m.root {
		b.WriteString("import myks as m\n\n")
		b.WriteString("env = m.Environment {\n")
		writeKclEntries(b, node.envValues, 4, false)
		m.writeApplications(b, node, 4, false)
		b.WriteString("}\n")
		return b.String()
	}

	usesMyks := node.env != nil || len(node.declared) > 0
	if usesMyks {
		b.WriteString("import myks as m\n")
	}
	fmt.Fprintf(b, "import %s as parent\n\n", packagePath(parent.dir))

	hasPatch := len(node.envPatch)+len(node.appPatches) > 0
	levelVar := "env"
	if hasPatch || node.env != nil {
		// A leaf wraps the level in finalize, so the union needs its own name.
		levelVar = "_lvl"
	}

	fmt.Fprintf(b, "%s = parent.env | {\n", levelVar)
	if node.env != nil {
		fmt.Fprintf(b, "    id = %q\n", node.env.ID)
	}
	writeKclEntries(b, node.envValues, 4, true)
	m.writeApplications(b, node, 4, true)
	b.WriteString("}\n")

	expr := levelVar
	if hasPatch {
		b.WriteString("\n# TODO(myks migrate): the values below were computed by ytt logic that the converter\n")
		b.WriteString("# cannot translate to KCL; they are frozen here as literals from the legacy-resolved\n")
		b.WriteString("# output. Replace them with KCL derivations (see docs/migration.md).\n")
		b.WriteString("_patch = {\n")
		writeKclEntries(b, node.envPatch, 4, true)
		if len(node.appPatches) > 0 {
			b.WriteString("    applications: {\n")
			for _, name := range slices.Sorted(maps.Keys(node.appPatches)) {
				fmt.Fprintf(b, "        %s: ", kclKey(name))
				writeKclValue(b, node.appPatches[name], 8, true)
				b.WriteString("\n")
			}
			b.WriteString("    }\n")
		}
		b.WriteString("}\n")
		expr = levelVar + " | _patch"
	}

	if node.env != nil {
		fmt.Fprintf(b, "env = m.finalize(%s)\n", expr)
	} else if hasPatch {
		fmt.Fprintf(b, "env = %s\n", expr)
	}
	return b.String()
}

// writeApplications renders a level's applications block: `m.App` declarations for
// applications rostered at this level and dict-union overrides for inherited ones.
func (m *migrator) writeApplications(b *strings.Builder, node *migNode, indent int, merge bool) {
	if len(node.declared)+len(node.overrides) == 0 {
		return
	}
	pad := strings.Repeat(" ", indent)
	sep := " = "
	if merge {
		sep = ": "
	}
	fmt.Fprintf(b, "%sapplications%s{\n", pad, sep)

	names := slices.Sorted(maps.Keys(node.declared))
	for _, name := range names {
		app := node.declared[name]
		fmt.Fprintf(b, "%s    %s = m.App {", pad, kclKey(name))
		if len(app.values) == 0 && app.proto == name {
			b.WriteString("}\n")
			continue
		}
		b.WriteString("\n")
		if app.proto != name {
			fmt.Fprintf(b, "%s        proto = %q\n", pad, app.proto)
		}
		writeKclEntries(b, app.values, indent+8, false)
		fmt.Fprintf(b, "%s    }\n", pad)
	}

	for _, name := range slices.Sorted(maps.Keys(node.overrides)) {
		fmt.Fprintf(b, "%s    %s: ", pad, kclKey(name))
		writeKclValue(b, node.overrides[name], indent+4, true)
		b.WriteString("\n")
	}

	fmt.Fprintf(b, "%s}\n", pad)
}

// writeKclEntries renders a map's entries, one per line, keys sorted. In merge style
// (dict-union patches) map values use `key: {...}` so nested dicts merge instead of
// replacing; everything else uses `key = value`.
func writeKclEntries(b *strings.Builder, values map[string]any, indent int, merge bool) {
	pad := strings.Repeat(" ", indent)
	for _, key := range slices.Sorted(maps.Keys(values)) {
		value := values[key]
		if _, isMap := value.(map[string]any); isMap && merge {
			fmt.Fprintf(b, "%s%s: ", pad, kclKey(key))
		} else {
			fmt.Fprintf(b, "%s%s = ", pad, kclKey(key))
		}
		writeKclValue(b, value, indent, merge)
		b.WriteString("\n")
	}
}

func writeKclValue(b *strings.Builder, value any, indent int, merge bool) {
	pad := strings.Repeat(" ", indent)
	switch typed := value.(type) {
	case map[string]any:
		if len(typed) == 0 {
			b.WriteString("{}")
			return
		}
		b.WriteString("{\n")
		writeKclEntries(b, typed, indent+4, merge)
		b.WriteString(pad)
		b.WriteString("}")
	case []any:
		if len(typed) == 0 {
			b.WriteString("[]")
			return
		}
		b.WriteString("[\n")
		for _, element := range typed {
			b.WriteString(pad)
			b.WriteString("    ")
			// List elements are fresh values, not unions: always assign style.
			writeKclValue(b, element, indent+4, false)
			b.WriteString("\n")
		}
		b.WriteString(pad)
		b.WriteString("]")
	default:
		b.WriteString(kclScalar(value))
	}
}

func kclScalar(value any) string {
	switch typed := value.(type) {
	case nil:
		return "None"
	case bool:
		if typed {
			return "True"
		}
		return "False"
	case string:
		return strconv.Quote(typed)
	case float64:
		formatted := strconv.FormatFloat(typed, 'f', -1, 64)
		if !strings.ContainsAny(formatted, ".eE") && !math.IsInf(typed, 0) {
			formatted += ".0"
		}
		return formatted
	case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64:
		return fmt.Sprintf("%d", typed)
	default:
		// Uncommon YAML types (timestamps, binary): keep the value as a string literal.
		return strconv.Quote(fmt.Sprintf("%v", typed))
	}
}

func kclKey(key string) string {
	if isKclIdentifier(key) {
		return key
	}
	return strconv.Quote(key)
}
