name: flow-pr

'on': pull_request

jobs:
  lint:
    uses: ./.github/workflows/job-lint.yml
  test:
    uses: ./.github/workflows/job-test.yml

  nix-update:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      actions: read
      contents: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # use more powerful token to trigger subsequent workflows
          token: ${{ secrets.MYKSO_BOT_GITHUB_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@1ca7d21a94afc7c957383a2d217460d980de4934 # v31.10.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update nix flake
        run: nix run '.#nix-update' -- --flake myks --version=skip

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        with:
          gpg_private_key: ${{ secrets.MYKSO_BOT_GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: 'chore: nix-update'
          commit_user_name: Mykso Bot
          commit_user_email: 135390787+mykso-bot@users.noreply.github.com

      - name: Set commit status
        # When running on a PR, set the commit status on the latest commit in
        # the branch. Otherwise, the PR will be waiting for the commit status
        # indefinitely. This, in particular, blocks Renovate from merging PRs
        # automatically.
        # If running on a push, set the commit status on the current commit.
        env:
          GH_TOKEN: ${{ github.token }}
          COMMIT_SHA: ${{ steps.commit.outputs.commit_hash || github.event.pull_request.head.sha || github.sha }}
          DESCRIPTION: ${{ steps.commit.outputs.changes_detected == 'true' && 'New changes have been committed' || 'Flake is up to date' }}
        run: |
          gh api repos/${{ github.repository }}/statuses/$COMMIT_SHA \
            -f state=success \
            -f context=nix-update \
            -f "description=$DESCRIPTION"
