name: flow-pr

on: pull_request

jobs:
  lint:
    uses: ./.github/workflows/job-lint.yml
  test:
    uses: ./.github/workflows/job-test.yml
  nix-update:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      actions: read
      contents: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # use more powerful token to trigger subsequent workflows
          token: ${{ secrets.MYKSO_BOT_GITHUB_TOKEN }}
      - uses: cachix/install-nix-action@91a071959513ca103b54280ac0bef5b825791d4d # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update nix flake
        run: nix run github:Mic92/nix-update -- --flake myks --version=skip
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6
        with:
          gpg_private_key: ${{ secrets.MYKSO_BOT_GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Commit changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5.1.0
        with:
          commit_message: 'chore: nix-update'
          commit_user_name: Mykso Bot
          commit_user_email: 135390787+mykso-bot@users.noreply.github.com
      - name: Set commit status
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          context: nix-update
          description:
            ${{ steps.commit.outputs.changes_detected == 'true' && 'New changes
            have been committed' || 'Flake is up to date' }}
          # When running on a PR, set the commit status on the latest commit in
          # the branch. Otherwise, the PR will be waiting for the commit status
          # indefinitely. This, in particular, blocks Renovate from merging PRs
          # automatically.
          # If running on a push, set the commit status on the current commit.
          sha:
            ${{ steps.commit.outputs.commit_hash ||
            github.event.pull_request.head.sha || github.sha }}
          status: success
