name: 'job-lint'

'on':
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          cache: false
          go-version-file: go.mod

      - name: Install gofumpt
        # TODO: ensure renovate detects this version
        run: go install mvdan.cc/gofumpt@v0.9.2

      - name: Check code formatting
        run: |
          set -euo pipefail
          gofumpt -l $( \
              git diff-tree -r --no-commit-id --name-only --diff-filter=ACMRT \
                "origin/$GITHUB_BASE_REF..origin/$GITHUB_HEAD_REF" \
              | grep '\.go$' \
            ) \
            | tee /dev/stderr \
            | test $(wc -l) -eq 0

      - name: Install mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - name: Run golangci-lint
        run: golangci-lint run
